# Generated by Django 4.2.2 on 2023-06-13 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IQ_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('date_passed', models.DateTimeField(auto_now=True)),
                ('login_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unique_login')),
            ],
        ),
        migrations.CreateModel(
            name='EQ_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=5)),
                ('date_passed', models.DateTimeField(auto_now=True)),
                ('login_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unique_login')),
            ],
        ),
    ]
