# Generated by Django 4.2.2 on 2023-06-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_test',
            name='login_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unique_login', unique=True),
        ),
        migrations.AlterField(
            model_name='iq_test',
            name='login_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unique_login', unique=True),
        ),
    ]
